### ISSUE TITLE
Lack of data

### ISSUE THREAD

**Issue by Nikkey13** [jeffchy/Learning-Numeral-Embeddings#1]
Can you please add wikidata train and test files, so that we can both reproduce your code and watch the data it relies on, thank you

**Comment by jeffchy** [comment]
Hi, sorry for the late response. As the wiki data is too big, we show how we obtain the data.
You can download the latest Wikipedia dumps here https://dumps.wikimedia.org/enwiki/20210101/, we obtained the data from the "Articles, templates, media/file descriptions, and primary meta-pages." section. An example download URL: https://dumps.wikimedia.org/enwiki/20210101/enwiki-20210101-pages-articles1.xml-p1p41242.bz2 

We downloaded about 20 of these files, and preprocess it using this python script.
https://github.com/jeffchy/Learning-Numeral-Embeddings/blob/master/pytorch-sgn/data/wikipedia/process_wiki.py
