### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by yns2018** [jeffchy/Learning-Numeral-Embeddings#2]
Hi，I hava read your paper named “Learning Numeral Embeddings” ,which is excellent. But I meet some problems when I was learning the code. There is error in file named experiments/probing/src/create_embedding.py.

FileNotFoundError：
numerals = pickle.load(open('../mag_num/data/numerals_mag_infre.pkl', 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: '../mag_num/data/numerals_mag_infre.pkl'

 How is this file generated? Thank you very much

**Comment by jeffchy** [comment]
Hi, this is the code about the probing experiment, which is not the main result, and I did not include these data files in the repo.
This .pkl contains infrequent numerals collect from a dataset and this .py file load the .pkl and creates embedding from the numerals using our method. 
You can find the data structure of this .pkl in [here](https://github.com/jeffchy/Learning-Numeral-Embeddings/blob/51ac0f489f4d9b66886508ed4f05ac30f94b0046/pytorch-sgn/experiments/mag_num/MagNumEvaluator.py#L16) it should be simply an array of numerals in this scenario.
